### PR TITLE
Revamp app

### LINKED ISSUE #11: Revamp app to use latest conventions
Compare ionic-conference-app and ionic-super-starter to current app and update app with latest conventions

---
**Acceptance Test**: Demonstrate working application with modified code

### PR DESCRIPTION
**Pull request by rhefner1**
Fixes #11

### CODE REVIEW

**Comment by rhefner1** [comment]
@ceelias some linting issues: https://travis-ci.org/cookomatic/cookomatic-app/builds/201247011#L1789

**Comment by ceelias** [comment]
@rhefner1 It looks like it's complaining about the imports in the pages.ts so I don't think there is anyway around those. Correct me if I'm wrong.

**Comment by rhefner1** [comment]
@ceelias Looks like an `Unused import` error. Just remove them!

**Review by ceelias — APPROVED** [review]
Looks good!

**Pull request merged**
